Fix compile error TS2605: JSX element type 'Swipeout' is not a constructor function for JSX elements. Property 'render' is missing in type 'Swipeout'.